services:
  # Django Backend API
  - type: web
    name: todo-backend
    env: python
    plan: free
    buildCommand: cd todo-backend && chmod +x build.sh && ./build.sh
    startCommand: cd todo-backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True
      - key: CORS_ALLOWED_ORIGINS
        value: https://todo-frontend.onrender.com
    autoDeploy: true

  # React Frontend
  - type: web
    name: todo-frontend
    env: static
    plan: free
    buildCommand: cd todo-frontend && npm install && npm run build
    staticPublishPath: ./todo-frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com
    autoDeploy: true

databases:
  - name: todo-database
    databaseName: todo_db
    user: todo_user
    plan: free 